name: NoOby
main: me.angelofdev.NoOby.NoOby
version: 1.0.2
website: http://derpmc.com
description: >
             Makes Obsidian break like Glass but makes Glass & other unobtainable blocks to drop like normal blocks.
author: AngelofDev