name: NoOby
main: me.angelofdev.NoOby.NoOby
version: 1.0.3
website: http://derpmc.com
description: >
             Enable/Disable drops for unbreakable blocks eg.Glass/Glowstone. Enable/Disable Obsidian drops.
author: AngelofDev